
name: mechint
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cpuonly
  - pip
  - pip:
      - numpy
      - matplotlib
      - scikit-learn
      - transformers
      - datasets
      - sentence-transformers
      - streamlit
      - networkx
      - tqdm
      - einops
      - typer
      - rich
      - wandb
      - black
      - ruff
      - mypy
      - pytest
